### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by Ishneetkaur** [not-an-aardvark/snoowrap#139] opened 2018-04-23 16:27 UTC
I am getting error, i have tried using continueAfterRatelimitError: true, requestDelay: 1000. But nothing is working.
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
 Error: snoowrap refused to continue because reddit's ratelimit was exceeded. For more information about reddit's ratelimit, please consult reddit's API rules at https://github.com/reddit/reddit/wiki/API.
     at snoowrap._awaitRatelimit (/opt/www/cron/node_modules/snoowrap/dist/request_handler.js:155:11)
     at /opt/www/cron/node_modules/snoowrap/dist/request_handler.js:81:18
     at tryCatcher (/opt/www/cron/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/opt/www/cron/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/opt/www/cron/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromiseCtx (/opt/www/cron/node_modules/bluebird/js/release/promise.js:606:10)
     at Async._drainQueue (/opt/www/cron/node_modules/bluebird/js/release/async.js:138:12)
     at Async._drainQueues (/opt/www/cron/node_modules/bluebird/js/release/async.js:143:10)
     at Immediate.Async.drainQueues (/opt/www/cron/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:672:20)
     at tryOnImmediate (timers.js:645:5)
     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by not-an-aardvark** [comment] 2018-04-23 16:43
Could you give an example of your code that causes this error?

**Comment by Ishneetkaur** [comment] 2018-04-23 17:15
```
const Snoowrap = require('snoowrap');
const Snoostorm = require('snoostorm');
const r = new Snoowrap({
    userAgent: USER_AGENT,
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    username: USERNAME,
    password: PASSWORD,
    refreshToken: REFRESH_TOKEN,
    accessToken: ACCESS_TOKEN
});

r.config({continueAfterRatelimitError: true, requestDelay: 1000});

const client = new Snoostorm(r);

const stream = client.SubmissionStream({
    'subreddit': subreddits,
    'results': 10,
    'pollTime': 1000 
});

stream.on('submission', (data) => {
    //process data
});

stream.on('error', (error) => {
    /** handle errors */
});
```

**Comment by not-an-aardvark** [comment] 2018-04-23 20:01
Is it possible that you're running multiple instances of this script at the same time, or that you're using the client ID for multiple different things outside of this snoowrap instance? If you're sending a single request per second, I think you would only exceed the ratelimit if there is something else also sending requests from that app.

**Comment by SidneyNemzer** [comment] 2018-04-24 03:55
I've found that a bot I created was allowed less than 60 requests per minute, because it was a new user. Maybe that's what is happening in this case?

**Comment by Ishneetkaur** [comment] 2018-04-24 15:48
No. It is not being used.

**Comment by SidneyNemzer** [comment] 2018-04-24 16:38
> there are two "ratelimits" to be aware of -- the regular 60 requests/minute ratelimit imposed on all API clients, and an additional timer on creating content imposed on accounts with low karma

Now that you mention it, that sounds right. But the bot I was testing was making a request, I believe, every 4 seconds but it was still running out of requests. I was only using the comment-streaming functionality, not creating any content. I haven't worked on it in a while, I'll have to investigate again.

**Comment by Ishneetkaur** [comment] 2018-04-27 17:41
Could you tell if i could try something else to fix this?

**Comment by not-an-aardvark** [comment] 2018-04-27 17:44
What is the output if you add `r.config({debug: true})` after creating the snoowrap instance?

**Comment by Ishneetkaur** [comment] 2018-05-25 19:29
Using the following code
```
const r = new Snoowrap({
    userAgent: USER_AGENT,
    clientId: CLIENT_ID,
    clientSecret: CLIENT_SECRET,
    username: USERNAME,
    password: PASSWORD
});

r.config({continueAfterRatelimitError: true, debug: true});

const client = new Snoostorm(r);
stream = client.SubmissionStream({
     subreddit: subreddits,
      results: 10,
      pollTime: 1000
});
stream.on('submission', (data) => {
 // data has continueAfterRatelimitError as false.
});
```

I am getting the following:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: snoowrap refused to continue because reddit's ratelimit was exceeded. For more information about reddit's ratelimit, please consult reddit's API rules at https://github.com/reddit/reddit/wiki/API.
at snoowrap._awaitRatelimit (/opt/www/cron/node_modules/snoowrap/dist/request_handler.js:155:11)
at /opt/www/cron/node_modules/snoowrap/dist/request_handler.js:81:18
at tryCatcher (/opt/www/cron/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by SpyTec** [comment] 2019-06-25 11:55
Since I couldn't figure it out right away, does this happen some time or right away? If it's right away then we will have to look at it, otherwise it might be Snoostorm being overzealous with its requests.

Closing this as I believe it to be the former, you should open an issue with SnooStorm about it

**Closed by SpyTec** 2019-06-25 11:55 UTC
Labels: bug

**Comment by SpyTec** [comment] 2019-06-25 12:35
Right, I misread the report. I tried reproducing it but I couldn't. When I used the code you sent and looked at `_awaitRatelimit()` I could not trigger the exception.

Remember that you have to set the config before making any requests
