### ISSUE TITLE
Always getting a 'Promise chain rejection' on every call

### ISSUE THREAD

**Issue by Gadzev** [not-an-aardvark/snoowrap#68] opened 2017-02-12 16:15 UTC
No matter what i use snoowrap for i always get a `Unhandled rejection TypeError: Promise chain rejection: Cannot read property 'entries' of undefined.`

Its the same error over and over. It will return what is suppose to return and then give me this error. 

Anyone had any similar issues?

**Comment by not-an-aardvark** [comment] 2017-02-12 19:07
Can you give an example of code that causes this issue?

Also, what version of Node are you using?

**Comment by Gadzev** [comment] 2017-02-12 19:29
I am sure i am using this wrong so bear with me here. I wan't to use this with react so i was just testing what the output will be in the console.

For example if i did `r.getComment('d1xchqn').body.then(console.log);` it would print the body in the console and then give me the error. 

I am using node v6.9.5

**Comment by not-an-aardvark** [comment] 2017-02-12 19:34
Hmm, that's odd -- the same code seems to work for me on Node 6.9.5 without printing an error.

What are you using to authenticate? (You can omit the credentials themselves -- I'm just wondering if the error only occurs with a particular type of authentication for some reason.)

Also, is there a stack trace?

**Comment by Gadzev** [comment] 2017-02-12 21:20
I am doing everything like in the documentation. I have used the reddit-oauth-helper to setup the config for snoowrap. The error seems to come from bluebird.js

Maybe some of the other dependencies i am using are causing the problem or i am using snoowrap wrong altogether. I will try and experiment see if i can make the error go away. 

One thing i didn't try is using snoowrap from the backend instead of the client side but i don't want to make more API calls than i need to.

**Comment by not-an-aardvark** [comment] 2017-02-12 21:24
Sorry, I'm a bit confused -- are you running snoowrap in a browser or in Node?

There are multiple documented ways to use snoowrap. I'm asking for specifics about what you're doing so that I can help figure out what's wrong, or fix a bug if the problem is in snoowrap itself. Instructions that would allow me to reproduce the issue would be very useful.

**Comment by Gadzev** [comment] 2017-02-12 22:21
I will post a code sample with everything you need once im home.

**Comment by archcorsair** [comment] 2017-02-25 07:10
Long trip home.

**Comment by Gadzev** [comment] 2017-02-25 15:09
Sorry i totally forgot about this thanks for reminding me. You can close this it was a problem with the pc i was using at the time nothing with snoowrap.

**Comment by not-an-aardvark** [comment] 2017-02-25 18:32
Thanks for the update. Closing this issue.

**Closed by not-an-aardvark** 2017-02-25 18:32 UTC
