### ISSUE TITLE
How old can posts with filter time: 'day' be?

### ISSUE THREAD

**Issue by matthias-herrmann** [not-an-aardvark/snoowrap#128] opened 2018-01-19 13:17 UTC
Task is to get all posts of the current day all 24 hours (with a scheduled task), so no post should get fetched twice. 
I've used the `search` function like this:

```
let todayPosts = await subreddit.search({
        time: 'day'
});
```

But the returned result contains posts older than 24 hours - my unit test which throws an assertion error:

>     it('should only contain posts created today', async function() {
>             let utcMillisecondsNow = new Date().getTime() / 1000;
> 
>             /**
>              * Applies for all posts
>              */
>             for (let i = 0; i < todaysPosts.length; i++) {
>                 const post = todaysPosts[i];
>                 
>                 let utcPostCreated = post.created_utc;
>                 let utcDifference = utcMillisecondsNow - utcPostCreated; 
>                 utcDifference /= (60*60); // [h]
> 
>                 /**
>                  * difference should be less than 24.0 hours
>                  */
>                 assert.equal(utcDifference < 24, true);
>             }
>         });
>

**Comment by not-an-aardvark** [comment] 2018-01-19 15:06
Can you post the output when you use `r.config({ debug: true })` and run it again?

In general, all the filtering is done on reddit's end, so if it's returning an incorrect result then it would probably be a bug in reddit's API and not in snoowrap.

**Comment by matthias-herrmann** [comment] 2018-01-19 15:45
@not-an-aardvark The request looks like this in the debug log:
 
> https://oauth.reddit.com/r/<subreddit>/search?raw_json=1&count=9999&subreddit=ArkEcosystem&restrictSr=true&syntax=plain&t=day&restrict_sr=true

So yes, this is on reddit's end. I looked up the corresponding documentation: https://www.reddit.com/dev/api#GET_search which shows no further information what is being meant by day (maybe less than 48 hours?), I'll try to figure that out - for now I will apply a filter on the search result.

**Comment by not-an-aardvark** [comment] 2018-01-19 15:53
Thanks for the response. I'll close this issue since it seems like the problem is on reddit's end.

**Closed by not-an-aardvark** 2018-01-19 15:53 UTC
