### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by strideynet** [not-an-aardvark/snoowrap#29] opened 2016-06-12 15:52 UTC
Hi, I'm a bit of a newb but I have been banging my head against this for hours now. Running node 6.2.1 and the version of your snoowrap from npm

`
r.get_comment("d462i0g").author.name.then(console.log);
`

and
`
r.get_submission("d462i0g").author.name.then(console.log);
`
both fail with TypeError: Cannot read property 'name' of undefined

However further up my page the following works:
`
r.get_inbox({
	filter: "mentions"
}).then(HandleMentions);
`
Where am I going wrong??!?

**Comment by strideynet** [comment] 2016-06-12 15:57
I have also tried running it with node server.js --harmony_proxies

**Comment by strideynet** [comment] 2016-06-12 15:59
Sorry please ignore. It turns out you need to run 6.2.1 with --harmony_proxies as well.

**Comment by not-an-aardvark** [comment] 2016-06-12 17:37
Are you sure you're running node v6.2.1? I don't think it should require the --harmony_proxies flag.

The following worked for me:

```
$ node --version
v6.2.1
$ node
```
```js
var r = new (require('snoowrap'))(require('./oauth_info.json'));

r.get_comment("d462i0g").author.name.then(console.log);
> strideynet
```

**Comment by strideynet** [comment] 2016-06-12 18:44
Quite odd. Whenever I remove the flag it fails.

**Comment by strideynet** [comment] 2016-06-12 18:44
I can confirm im on 6.2.1

**Comment by not-an-aardvark** [comment] 2016-06-12 18:54
That's definitely strange. Do you think you could provide a larger code sample to help me figure out what's going on? I don't think the --harmony_proxies flag should have any effect at all in node 6.

**Comment by strideynet** [comment] 2016-06-12 19:04
http://stackoverflow.com/questions/10665892/enable-harmony-proxies-in-nodejs
Just seen this. I'll get a copy of my code when im at my pc for you.

**Comment by not-an-aardvark** [comment] 2016-06-12 19:08
Thanks. Regarding the stackoverflow page, that flag was necessary in 4 and 5 since harmony proxies hadn't been implemented fully by v8, but as far as I know it's not necessary in node 6 since harmony proxies are available by default.

**Comment by not-an-aardvark** [comment] 2016-06-21 13:30
I'm going to close this as "cannot reproduce" for the time being to stay organized, but feel free to continue the discussion if you're still experiencing the issue.

**Closed by not-an-aardvark** 2016-06-21 13:30 UTC
