### ISSUE TITLE
const not supported by safari

### ISSUE THREAD

**Issue by mschwartz** [not-an-aardvark/snoowrap#32] opened 2016-06-28 21:36 UTC
Works great in the browser if it's chrome :)

Safari doesn't allow const.

I could babel the code, but I really prefer to just use the .min.js.

Also, in chrome while emulating iPhone 6, you are catching some error involving google maps API.

Maybe the ExtJS framework I'm using is causing the maps API error, but you shouldn't be catching it.

**Comment by mschwartz** [comment] 2016-06-28 21:40
If I make no calls to snoowrap, I don't see an error thrown.

If I call r.get_hot(), I get this:

![image](https://cloud.githubusercontent.com/assets/329637/16433270/380d7b68-3d3e-11e6-962a-4d773fe2a36d.png)

**Comment by not-an-aardvark** [comment] 2016-06-28 22:08
Thanks for the report -- I'll look into seeing if I can get the browser build to work with Safari.

However, could you clarify what you mean when you say that snoowrap is catching a google maps API error?

**Comment by abdulhannanali** [comment] 2016-06-28 22:25
I think he means that you shouldn't be looking into that error because ExtJS framework might be the cause of it

**Comment by mschwartz** [comment] 2016-06-28 23:35
ExtJS is not the cause of it. Loading font awesome or google maps api from
Google servers causes the problem.

Aside from making robots, you'd think this is ideal for making mobile or
browser apps.

**Comment by not-an-aardvark** [comment] 2016-06-29 00:36
This was closed because I fixed the Safari issue, but I guess I'll reopen it for the google maps issue.

Would you mind providing sample code for how you're interacting with google maps/snoowrap? I can't think of how snoowrap would be interfering with your requests to the google maps API.

**Comment by mschwartz** [comment] 2016-06-29 03:32
It is ExtJS that is causing Google maps API to be yanked in, locally (e.g.
Not from a cdn). It's probably adding a script tag dynamically.

The issue is that the Maps API is fetching additional js files from cdn.

I've initiated a get_hot request and before it finishes, the Maps API
returns a "not logged in" status. It appears to me snoowrap is trying to
parse that response.

**Comment by not-an-aardvark** [comment] 2016-06-29 03:36
I see -- what makes you think that snoowrap is trying to parse that response?

(Sorry for asking so many questions, but I'm still not sure I understand what's going on.)

**Comment by mschwartz** [comment] 2016-06-29 13:30
Can you see the error snoowrap threw?  I included it in one of my previous comments here.  That' kind of output is not anything I've seen in any other JavaScript environment.  

Also, the issue only occurs when running the app in emulation mode in the developer tools.  The app runs fine as a desktop app.  The only difference is font awesome and google maps.

If I comment out snoowrap, the app works in emulation mode.

When I look at the network tab, I see the request to reddit succeeds, then after a few seconds the other requests for google assets succeed but the login auth to google apis fails and the error I see is thrown.  The .then() for the reddit request doesn't seem to be called.

What else can I tell you?

**Comment by not-an-aardvark** [comment] 2016-06-29 13:52
> When I look at the network tab, I see the request to reddit succeeds

What is the endpoint of the request to reddit that succeeds? snoowrap has to make a couple requests to reddit at first (to get an access token before it can start accessing the API directly).

From that screenshot, it seems like the request to https://oauth.reddit.com/hot?raw_json=1&count=9999 is failing, and that's causing the error that gets thrown. I think the issue with the google API login might be unrelated to snoowrap.

**Comment by mschwartz** [comment] 2016-06-29 14:26
I think I see what's going on.

When using the desktop framework, snoowrap is generating an **http** request to reddit.  When running in the mobile framework, snoowrap is generating an **https** request that is getting a 302 response.

Maybe have a look at what circumstances you are generating https requests?

The URL in my browser is not https.

**Comment by mschwartz** [comment] 2016-06-29 14:26
![image](https://cloud.githubusercontent.com/assets/329637/16455893/d423fa22-3dca-11e6-9093-f71ae4073b1a.png)

**Comment by not-an-aardvark** [comment] 2016-06-29 14:38
Hmm, it seems like reddit is redirecting the OAuth request to its mobile HTML site (http://m.reddit.com) since it identifies that you're on a mobile device based on the user-agent. That could be a bug with the reddit API.

Have you tried using a different user-agent with snoowrap?

**Comment by mschwartz** [comment] 2016-06-29 14:42
No, but I could try.

I'm using navigator.userAgent :)

**Comment by mschwartz** [comment] 2016-06-29 14:43
I am a bit confused by this, though:

![image](https://cloud.githubusercontent.com/assets/329637/16456566/2767fce0-3dcd-11e6-82ec-b9dbf43db86f.png)

The request URL is https.

**Comment by mschwartz** [comment] 2016-06-29 14:46
Using hardcoded user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

Still fails.

**Comment by not-an-aardvark** [comment] 2016-06-29 14:47
> I'm using navigator.userAgent :)

I had to guess, that's what is causing the issue. Reddit has some guidelines [here](/reddit/reddit/wiki/API#rules) on choosing a good user-agent string; basically, it sometimes does things unexpectedly if it thinks the request is coming from a browser trying to access the normal site.

Try making your user-agent something different, related to your app.

**Comment by not-an-aardvark** [comment] 2016-06-29 14:52
> I am a bit confused by this, though:

> ![image](https://cloud.githubusercontent.com/assets/329637/16456566/2767fce0-3dcd-11e6-82ec-b9dbf43db86f.png)

> The request URL is https.

That's as intended; in fact, all OAuth requests are required to use https. I'm not sure why reddit redirects to the `http:` version of its site, though.

**Comment by mschwartz** [comment] 2016-06-29 14:57
I don't know how reddit's server is able to detect mobile browser given that I'm passing giving it a user_agent that is the desktop browser's string.

Some more info:

![image](https://cloud.githubusercontent.com/assets/329637/16457040/f96ccc1a-3dce-11e6-8906-d6fff80c7618.png)

and

![image](https://cloud.githubusercontent.com/assets/329637/16457057/05f65cc6-3dcf-11e6-82a6-dba52026f286.png)

and

![image](https://cloud.githubusercontent.com/assets/329637/16457077/11709e54-3dcf-11e6-9069-0cdce659ea96.png)


those requests are not being redirected...

**Comment by mschwartz** [comment] 2016-06-29 14:58
Aha

![image](https://cloud.githubusercontent.com/assets/329637/16457124/375267a6-3dcf-11e6-973a-f0baeb41dc4c.png)

**Comment by not-an-aardvark** [comment] 2016-06-29 15:02
I went ahead and removed the image from your last comment as a precaution, since it contained your client credentials (in the "Authentication" header, encoded in base64). You may want to edit that out of the image.

**Comment by mschwartz** [comment] 2016-06-29 15:05
Appreciate it.  I fixed the image.

Anyhow, maybe you can override the user-agent header with user_agent configuration/option?

**Comment by not-an-aardvark** [comment] 2016-06-29 15:12
[In theory](/not-an-aardvark/snoowrap/blob/8e9d70ba2a20c5468f9d01b98e4c8775e002c854/src/request_handler.js#L146) snoowrap already does that, and it seems to set the header correctly in node, at least. I'm not sure why it's not working in your authentication request, though.

Just to make sure, are you setting the user-agent option as you construct the snoowrap instance? e.g.

```js
new snoowrap({
  user_agent: 'put the custom user-agent string here',
  client_id: 'foo',
  client_id: 'bar',
  refresh_token: 'baz'
})
```

**Comment by mschwartz** [comment] 2016-06-29 15:18
![image](https://cloud.githubusercontent.com/assets/329637/16457918/1c60a81a-3dd2-11e6-9a12-b542a1b004d6.png)

**Comment by not-an-aardvark** [comment] 2016-06-29 15:34
I can reproduce this. It seems like the user-agent header gets ignored when making requests from browsers.

**Comment by mschwartz** [comment] 2016-06-29 15:38
Awesome.

Now the question is if you can figure out how to override the header or contact Reddit and ask about the redirect.

**Comment by mschwartz** [comment] 2016-06-29 15:38
Also, I appreciate your patience and looking at this.

**Comment by not-an-aardvark** [comment] 2016-06-30 03:11
I decided to make another ticket for the user-agent issue (see #33) and close this one, since the original issue of `const` not working in safari should be fixed in the next update.

**Closed by not-an-aardvark** 2016-06-30 03:11 UTC
Labels: bug
