### ISSUE TITLE
How to submit a link including a flair

### ISSUE THREAD

**Issue by lilsweetkara** [not-an-aardvark/snoowrap#316] opened 2021-04-25 06:55 UTC
I am submitting links successfully with this code:

````
    const response = await redditAPI
      .getSubreddit('amihot')
      .submitLink(
        {
          title: newRedditPost.title + ' ' + subreddit.titlePostfix,
          url: newRedditPost.imageUrl
        }
      )
````

However, some subreddits _require_ the use of flairs. See for example this one: https://www.reddit.com/r/amihot/submit
The flair is actually mandatory.
How do I submit a flair as I post? I tried this:

````
    const response = await redditAPI
      .getSubreddit('amihot')
      .submitLink(
        {
          title: newRedditPost.title + ' ' + subreddit.titlePostfix,
          url: newRedditPost.imageUrl,
          flair: "Female"
        }
      )
````

But it didn't work.

Thanks!

Kara

**Comment by SpyTec** [comment] 2021-04-25 11:05
Hi,

Just opened #317 that will fix this. After it's been verified and merged I'll release a new version. 

I believe you will then be able to do:
```js
const linkFlairs = await redditAPI.getSubreddit('amihot').getLinkFlairTemplates()
const femaleFlair = linkFlairs.find(o => o.flair_text === 'Female')
const response = await redditAPI
  .getSubreddit('amihot')
  .submitLink(
    {
      title: newRedditPost.title + ' ' + subreddit.titlePostfix,
      url: newRedditPost.imageUrl,
      flair_id: femaleFlair.flair_template_id
    }
  )
```

If that doesn't work you might have to add `flair_text: ''` to the form as well. But I doubt it as it would only be used if you can edit the flair text

**Comment by lilsweetkara** [comment] 2021-04-25 11:24
I kind of need it tonight. Do you think I should just apply those changes
by hand  and use it like that for now?

I realize it's open source and i don't expect you to take on my own
problems. I am so sick of submitting by hand it's not funny :)
My husband has made a neat scheduler for submissions but I do need flairs.

Kara

**Comment by lilsweetkara** [comment] 2021-04-25 11:42
Wait a second, I just re-read your answer. I had assumed this was an
existing fix -- I just figured out you did it just for me!
I am passing this on to my personal software engineer (my husband!) right
now, and will confirm that it works.
THANK YOU!

**Comment by SpyTec** [comment] 2021-04-25 12:12
If the code in #317 works, let me know! But if you can't test it there is a way to add the functionality on your end by using [`Snoowrap#oauthRequest`](https://not-an-aardvark.github.io/snoowrap/snoowrap.html#oauthRequest__anchor). That way you don't have to wait for a new release of Snoowrap

```js
const linkFlairs = await r.oauthRequest({uri: 'r/amihot/api/flairselector', method: 'post', form: {is_newlink: true}}).then(res => res['choices'])
// above is equivalent to redditAPI.getSubreddit('amihot').getLinkFlairTemplates()
```

**Comment by lilsweetkara** [comment] 2021-04-25 12:19
Well, after you actually took your time to fix something that affects a
small fraction of your users, and even providing a shortcut for me, the
LEAST I can do is refuse the shortcut, and actually test this properly for
you.
I will let you know shortly.

**Comment by lilsweetkara** [comment] 2021-04-25 13:29
Bad news: it doesn't work. Don't merge!
Good news: we figured out what is wrong with it. Well, kind of.
The problem is in `_submit()`, which reads:

````
  _submit ({
    captcha_response, captchaResponse = captcha_response,
    captcha_iden, captchaIden = captcha_iden,
    kind,
    resubmit = true,
    send_replies = true, sendReplies = send_replies,
    crosspost_fullname,
    text,
    title,
    url,
    subreddit_name, subredditName = subreddit_name
  }) {
    return this._post({
      uri: 'api/submit', form: {
        api_type, captcha: captchaResponse, iden: captchaIden, sendreplies: sendReplies, sr: subredditName, kind, resubmit,
        crosspost_fullname, text, title, url
      }
    }).tap(handleJsonErrors(this)).then(result => this.getSubmission(result.json.data.id));
  }
````
When setting a flair, this function _receives_ the `flair_id`; however, it doesn't seem to use it in the `_post` call. I manually added it to the submit object, and -- guess what? -- it WORKS!

I tested this on normal posts, which don't require flairs; leaving the flair_id set as undefined doesn't seem to bother submission of posts that do NOT have flairs.

I hope my input was useful. I am sorry, I have only a superficial grasp of all of this, and I cannot provide a pull request. I hope this was helpful though...

**Comment by lilsweetkara** [comment] 2021-04-25 13:36
(I am a pilot and a model, I wrote this with the help of my dearest software engineer who actually explained things over to me, so please don't give me too much merit)

**Comment by SpyTec** [comment] 2021-04-25 15:56
> Bad news: it doesn't work. Don't merge!

That fix wouldn't have addressed submit not working, it just helps you with getting the `flairId` to add to the form

I didn't think of `submit()` having issues too, but I've addressed that in #318 now. It will add `flairId` as well as allowing people to add in any parameters we haven't defined. Thanks!

**Comment by lilsweetkara** [comment] 2021-04-25 22:56
I tested it, and it seems to work beautifully -- as long as both changes are applied.
Commands run by my little big helper:

````
   git clone https://github.com/not-an-aardvark/snoowrap.git
   cd snoowrap
   git pull origin feat/flair-templates-newlink
   git pull origin feat/submit-options
   npm install
   npm run compile
````
Run the code, and submitted one with flair, and YES, it's there!
The only catch is that it needs both changes to actually work. We are actually OK though.
When do you think you will release these fixes? This is not to hurry, just for us to know.

**THANK YOU**

**Comment by lilsweetkara** [comment] 2021-04-25 23:05
Is your discord user still SpyTec#9186 ? I sent a request but didn't work

**Comment by lilsweetkara** [comment] 2021-04-26 00:20
I submitted #319 -- after that I promise you I won't bother you again!

**Comment by SpyTec** [comment] 2021-04-26 14:54
With any luck I'll have a release out this week, but it depends on the level of testing that can be done to verify that the features function as they should and don't have any regressions

In the meantime `snoowrap#oauthRequest()` as I mentioned earlier can be used instead since uses the rate limiter we have

**Comment by lilsweetkara** [comment] 2021-05-01 05:28
I am using the "proper" calls with the patch for now. I wrote a "social poster" and your module is basically the heart of my little gem!
I will eventually want to place it somewhere other than my computer. How did the testing go? Do you think it's ready for release? IO don't mean to hurry you at all! I am just asking -- the only difference to me is that I apply the patches manually.

Thank you once again -- heartfelt "thanks"!

**Closed** 2021-05-15 01:45 UTC

**Comment by lilsweetkara** [comment] 2022-01-28 14:17
I am sorry for the noise... I was just wondering if these two branches made it into the main program?

* `feat/flair-templates-newlink`
* `feat/submit-options`

I am sorry if the answer is obvious, I don't know how to check
