### ISSUE TITLE
Failed to minify / request to be pre-compiled

### ISSUE THREAD

**Issue by jmaslin** [not-an-aardvark/snoowrap#132] opened 2018-02-20 19:03 UTC
When I am attempting to build my project I receive the following error (and proposed solution):

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/snoowrap/dist/helpers.js:151:55

Read more here: http://bit.ly/2tRViJ9
```

Direct link to docs: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by not-an-aardvark** [comment] 2018-02-20 19:32
Closing as a duplicate of https://github.com/not-an-aardvark/snoowrap/issues/100

**Closed by not-an-aardvark** 2018-02-20 19:32 UTC

**Comment by jmaslin** [comment] 2018-02-21 17:50
Sorry for opening a duplicate issue! Thanks for maintaining this project.
