### ISSUE TITLE
Incorrect typeDef on Listing.fetchAll and Listing.fetchMore

### ISSUE THREAD

**Issue by JoeJGast** [not-an-aardvark/snoowrap#303] opened 2021-01-04 09:36 UTC
currently the fetchAll/fetchMore methods are defined with types below
```typescript
  fetchMore(options: FetchMoreOptions):  Listing<T>;
  fetchAll(options?: FetchMoreOptions): Listing<T>;
```
This throws a typescript error when handling the promise returned by these functions.  They should be defined as
```typescript
  fetchMore(options: FetchMoreOptions): Promise<Listing>;
  fetchAll(options?: FetchMoreOptions): Promise<Listing>;
```

**Comment by SpyTec** [comment] 2021-01-04 11:25
Closing as duplicate of #221. Although this would be good in theory, it will not work correctly with proxies

I mentioned this in #296 

> snoowrap makes use of [proxies](https://github.com/not-an-aardvark/snoowrap#important-note-on-es6) which makes it possible to fetch items without having to await or use promises explicitly.
> 
> Your proposal means this will throw an error
> ```js
> export function multireddits (username: string): Promise<MultiReddit[]> {
>   return r.getUser(username).getMultireddits();
> }
> export function user (username: string): RedditUser {
>   return r.getUser(username);
> }
> ```

**Closed by SpyTec** 2021-01-04 11:25 UTC
